create schema [hospital];
USE [hospital];

CREATE TABLE sex_type
(
  SEX_TYPE_CODE INT CONSTRAINT PK_tblSex PRIMARY KEY IDENTITY(1,1),
  TYPE VARCHAR(1) NOT NULL
);

CREATE TABLE blood_type
(
  BLOOD_TYPE_CODE INT CONSTRAINT PK_tblBloodType PRIMARY KEY IDENTITY(1,1),
  BLOOD_CLASS VARCHAR(1) NOT NULL
);

CREATE TABLE cities
(
  CITY_CODE INT CONSTRAINT PK_tblCities PRIMARY KEY IDENTITY(1,1),
  CITY_NAME NVARCHAR(20) NOT NULL,
  POSTAL_CODE INT NOT NULL,
  CONSTRAINT PK_province FOREIGN KEY (PROVINCE_CODE) REFERENCES provinces(PROVINCE_CODE)
);

CREATE TABLE provinces
(
  PROVINCE_CODE INT CONSTRAINT PK_tblProvince PRIMARY KEY IDENTITY(1,1),
  NAME VARCHAR(20) NOT NULL
);

CREATE TABLE civil_status
(
  STATUS_CODE INT CONSTRAINT PK_civilStatus PRIMARY KEY IDENTITY(1,1),
  STATUS VARCHAR(20) NOT NULL
);

CREATE TABLE clinic_historic
(
  CLINIC_HISTORIC_CODE INT CONSTRAINT PK_clinigHistoric PRIMARY KEY IDENTITY(1,1),
  HISTORIC NVARCHAR(200) NOT NULL,
  CONSTRAINT PK_pacient FOREIGN KEY (PATIENT_CODE) REFERENCES patients(PATIENT_CODE)
);

CREATE TABLE parentship
(
  PARENTSHIP_CODE INT CONSTRAINT PK_parentship PRIMARY KEY IDENTITY(1,1),
  RELATIONSHIP_TYPE NVARCHAR(20) NOT NULL,
  REPETITION INT NOT NULL
);

CREATE TABLE phone_types
(
  PHONE_TYPE_CODE INT CONSTRAINT PK_phoneType PRIMARY KEY IDENTITY(1,1),
  PHONE_TYPE NVARCHAR(20) NOT NULL
);

CREATE TABLE people
(
  PERSON_CODE INT CONSTRAINT PK_person PRIMARY KEY IDENTITY(1,1),
  NAME NVARCHAR(20) NOT NULL,
  LAST_NAME NVARCHAR(30) NOT NULL
);

CREATE TABLE phones
(
  PHONE_CODE INT CONSTRAINT PK_phone PRIMARY KEY IDENTITY(1,1),
  PHONE_NUMBER VARCHAR(15) NOT NULL,
  CONSTRAINT PK_phoneType FOREIGN KEY (PHONE_TYPE_CODE) REFERENCES phone_types(PHONE_TYPE_CODE),
  CONSTRAINT PK_person FOREIGN KEY (PERSON_CODE) REFERENCES people(PERSON_CODE)
);

CREATE TABLE FAMILIES
(
  FAMILY_CODE INT CONSTRAINT PK_family PRIMARY KEY IDENTITY(1,1),
  CONSTRAINT PK_person FOREIGN KEY (PERSON_CODE) REFERENCES people(PERSON_CODE),
  CONSTRAINT PK_relative FOREIGN KEY (PERSON_CODE) REFERENCES people(PERSON_CODE),
  CONSTRAINT PK_parentship FOREIGN KEY (PARENTSHIP_CODE) REFERENCES parentship(PARENTSHIP_CODE)
);

CREATE TABLE document_type
(
  DOCUMENT_TYPE_CODE INT CONSTRAINT PK_documentType PRIMARY KEY IDENTITY(1,1),
  DOCUMENT_TYPE NVARCHAR(20) NOT NULL
);

CREATE TABLE ADDRESSES
(
  ADDRESS_CODE INT CONSTRAINT PK_address PRIMARY KEY IDENTITY(1,1),
  ADDRESS NVARCHAR(100) NOT NULL,
  CONSTRAINT PK_person FOREIGN KEY REFERENCES people(PERSON_CODE)
);

CREATE TABLE DOCUMENTS
(
  DOCUMENT_CODE INT CONSTRAINT PK_document PRIMARY KEY IDENTITY(1,1),
  DOCUMENT_NUMBER INT NOT NULL,
  CONSTRAINT PK_documentType FOREIGN KEY (DOCUMENT_TYPE_CODE) REFERENCES document_type(DOCUMENT_TYPE_CODE),
  CONSTRAINT PK_person FOREIGN KEY (PERSON_CODE) REFERENCES people(PERSON_CODE)
);

CREATE TABLE PATIENTS
(
  PATIENT_CODE INT CONSTRAINT PK_patient PRIMARY KEY IDENTITY(1,1),
  DATE VARCHAR(20),
  PHOTO VARCHAR(200),
  CONSTRAINT PK_person FOREIGN KEY (PERSON_CODE) REFERENCES people(PERSON_CODE),
  CONSTRAINT PK_tblBloodType FOREIGN KEY (BLOOD_TYPE_CODE) REFERENCES blood_type(BLOOD_CODE),
  CONSTRAINT PK_tblSex FOREIGN KEY (SEX_TYPE_CODE) REFERENCES sex_type(SEX_TYPE_CODE),
  CONSTRAINT PK_civilStatus FOREIGN KEY (STATUS_CODE) REFERENCES civil_status(STATUS_CODE),
  CONSTRAINT PK_tblCities FOREIGN KEY (CITY_CODE) REFERENCES cities(CITY_CODE)
);